openapi: 3.0.1
info:
  title: Redfast Tenant API
  version: "1.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://partner.redfast.com
paths:
  /v1/tenants/{external_tenant_id}:
    get:
      summary: Get an existing Redfast tenant
      description: Retrieves an existing tenant from the Redfast platform.
      tags:
        - Tenants
      parameters:
        - in: path
          name: external_tenant_id
          required: true
          schema:
            type: string
          description: Unique Partner Tenant ID
        - in: query
          name: partner_code
          required: true
          schema:
            type: string
          description: Partner Code assigned by Redfast
        - in: header
          name: rf-secret
          required: true
          schema:
            type: string
          description: Shared secret provided by Redfast (separate secrets for Test and Production)
      responses:
        "200":
          description: Tenant retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  external_tenant_id:
                    type: string
                    example: "tenant-123"
                  app_id:
                    type: string
                    example: "abc123app"
                  tag_url:
                    type: string
                    format: uri
                    example: "https://abc123app.redfastlabs.com/assets/redfast.js"
                  user_first_name:
                    type: string
                    example: "John"
                  user_last_name:
                    type: string
                    example: "Smith"
                  user_email:
                    type: string
                    format: email
                    example: "jsmith@myemail.com"
                  app_name:
                    type: string
                    example: "My App"
                  company_name:
                    type: string
                    example: "My Company"
                  app_domain:
                    type: string
                    example: "myco.com"
                  test_mode:
                    type: boolean
                    example: false
        "401":
          description: Unauthorized - Shared secret is incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: "invalid_secret"
        "404":
          description: Not Found - Tenant not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: "not_found"
                  message:
                    type: string
                    example: "resource not found"
