openapi: 3.0.1
info:
  title: Redfast Session Redirect API
  version: "1.0"
servers:
  - url: https://partner.redfast.com
paths:
  /v1/session/redirect:
    get:
      summary: Redirects user to Pulse (Redfast Frontend)
      description: >
        Redirects a user to pulse.redfast.com, optionally to a specified path, and attaches the session token.
        If no valid session, the user will be sent to the login page.
      tags:
        - Redirect
      parameters:
        - name: session_token
          in: query
          required: true
          schema:
            type: string
          description: >
            Redfast session token that authenticates the user for frontend access.
        - name: redirect_url
          in: query
          required: false
          schema:
            type: string
          description: >
            Optional relative path (e.g., `/welcome`) to redirect to after login. 
            Defaults to root if not provided.
      responses:
        "302":
          description: Redirects the user to Pulse frontend
          headers:
            Location:
              description: Final URL to redirect the browser
              schema:
                type: string
                example: https://pulse.redfast.com/welcome?session_token=eyJhbGciOi...
        "401":
          description: Unauthorized - Invalid session token or redirect target
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    enum: [unauthorized]
                    example: unauthorized
                  message:
                    type: string
                    example: Invalid or expired session token
