openapi: 3.0.1
info:
  title: Redfast Tenant API
  version: '1.0'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://partner.redfast.com
paths:
  /v1/tenants:
    patch:
      summary: Update a Redfast tenant
      description: Updates a Redfast tenant's information or public key.
      tags:
        - Tenants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - external_tenant_id
                - partner_code
              properties:
                external_tenant_id:
                  type: string
                  description: Unique Partner Tenant ID
                  example: tenant-123
                partner_code:
                  type: string
                  description: Partner Code assigned by Redfast
                  example: recurly
                app_domain:
                  type: string
                  description: (Optional) Top-level domain of the app
                  example: example.com
                api_key:
                  type: string
                  description: (Optional) API key used for integration
                  example: abcd1234apikey
      parameters:
        - in: header
          name: rf-secret
          required: true
          schema:
            type: string
          description: >-
            Shared secret provided by Redfast (separate secrets for Test and
            Production)
      responses:
        '200':
          description: Tenant updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: string
                    example: updated
                  external_tenant_id:
                    type: string
                    example: tenant-123
                  app_id:
                    type: string
                    example: abc123app
                  tag_url:
                    type: string
                    format: uri
                    example: https://abc123app.redfastlabs.com/assets/redfast.js
                  test_mode:
                    type: boolean
                    example: false
              examples:
                New Example:
                  summary: New Example
                  value: ''
                OK:
                  summary: OK
                  value:
                    success: true
                    status: updated
                    external_tenant_id: tenant-123
                    app_id: abc123app
                    tag_url: https://abc123app.redfastlabs.com/assets/redfast.js
                    test_mode: false
        '401':
          description: Unauthorized - Shared secret is incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: invalid_secret
        '404':
          description: Not Found - Requested resource was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: not_found
                  message:
                    type: string
                    example: resource not found
        '422':
          description: Unprocessable Entity - Invalid or missing information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: missing_or_invalid_info
                  message:
                    type: string
                    example: partner_code missing
                  external_tenant_id:
                    type: string
                    example: tenant-123
