openapi: 3.0.1
info:
  title: Redfast Tenant API
  version: '1.0'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: https://partner.redfast.com
paths:
  /v1/tenants:
    post:
      summary: Create a new Redfast tenant
      description: Creates a new tenant on the Redfast platform.
      tags:
        - Tenants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - company_name
                - external_tenant_id
                - app_name
                - app_domain
                - user_email
                - user_first_name
                - user_last_name
                - partner_code
                - api_key
              properties:
                company_name:
                  type: string
                  example: My Company
                external_tenant_id:
                  type: string
                  example: tenant-123
                app_name:
                  type: string
                  example: My App
                app_domain:
                  type: string
                  example: example.com
                user_email:
                  type: string
                  format: email
                  example: admin@example.com
                user_first_name:
                  type: string
                  example: John
                user_last_name:
                  type: string
                  example: Doe
                partner_code:
                  type: string
                  example: recurly
                api_key:
                  type: string
                  example: abcd1234apikey
      parameters:
        - in: header
          name: rf-secret
          required: true
          schema:
            type: string
          description: >-
            Shared secret provided by Redfast (separate secrets for Test and
            Production)
      responses:
        '200':
          description: Tenant provision started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  status:
                    type: string
                    example: provisioning_started
                  external_tenant_id:
                    type: string
                    example: tenant-123
                  app_id:
                    type: string
                    example: abc123app
                  tag_url:
                    type: string
                    format: uri
                    example: https://abc123app.redfastlabs.com/assets/redfast.js
                  test_mode:
                    type: boolean
                    example: false
              examples:
                OK:
                  summary: OK
                  value:
                    success: true
                    status: provisioning_started
                    external_tenant_id: tenant-123
                    app_id: abc123app
                    tag_url: https://abc123app.redfastlabs.com/assets/redfast.js
                    test_mode: false
        '401':
          description: Unauthorized - Shared secret is incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: invalid_secret
        '404':
          description: Not Found - Requested resource was not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: not_found
                  message:
                    type: string
                    example: resource not found
        '409':
          description: Conflict - Tenant has already been provisioned
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: already_provisioned
                  external_tenant_id:
                    type: string
                    example: tenant-123
        '422':
          description: Unprocessable Entity - Invalid or missing information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  status:
                    type: string
                    example: missing_or_invalid_info
                  message:
                    type: string
                    example: partner_code missing
                  external_tenant_id:
                    type: string
                    example: tenant-123
